from exception import X

print(X)